In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/Wholesale customers data.csv")
df

Channel  Region  Fresh   Milk  Grocery   Frozen  Detergents_Paper  \
0          2       3  12669   9656   7561.0    214.0            2674.0   
1          2       3   7057   9810   9568.0   1762.0            3293.0   
2          2       3   6353   8808   7684.0   2405.0            3516.0   
3          1       3  13265   1196   4221.0   6404.0             507.0   
4          2       3  22615   5410   7198.0   3915.0            1777.0   
..       ...     ...    ...    ...      ...      ...               ...   
411        1       3      3  12051  16027.0  13135.0             182.0   
412        1       3  39228   1431    764.0   4510.0              93.0   
413        2       3  14531  15488  30243.0    437.0           14841.0   
414        1       3  10290   1981   2232.0   1038.0             168.0   
415        1       3   2787   1698   2510.0     65.0             477.0   

     Delicassen  
0        1338.0  
1        1776.0  
2        7844.0  
3        1788.0  
4        5185.0  
..          ...  
411      2204.0  
412      2346.0  
413      1867.0  
414      2125.0  
415        52.0  

[416 rows x 8 columns]

In [ ]:
df.head()

Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656   7561.0   214.0            2674.0      1338.0
1        2       3   7057  9810   9568.0  1762.0            3293.0      1776.0
2        2       3   6353  8808   7684.0  2405.0            3516.0      7844.0
3        1       3  13265  1196   4221.0  6404.0             507.0      1788.0
4        2       3  22615  5410   7198.0  3915.0            1777.0      5185.0

In [ ]:
df.tail()

Channel  Region  Fresh   Milk  Grocery   Frozen  Detergents_Paper  \
411        1       3      3  12051  16027.0  13135.0             182.0   
412        1       3  39228   1431    764.0   4510.0              93.0   
413        2       3  14531  15488  30243.0    437.0           14841.0   
414        1       3  10290   1981   2232.0   1038.0             168.0   
415        1       3   2787   1698   2510.0     65.0             477.0   

     Delicassen  
411      2204.0  
412      2346.0  
413      1867.0  
414      2125.0  
415        52.0

In [ ]:
df.isna().sum()

Channel             0
Region              0
Fresh               0
Milk                0
Grocery             1
Frozen              1
Detergents_Paper    3
Delicassen          2
dtype: int64

In [ ]:
df.columns

Index(['Channel', 'Region', 'Fresh', 'Milk', 'Grocery', 'Frozen',
       'Detergents_Paper', 'Delicassen'],
      dtype='object')

In [ ]:
#To fill the mising values

df1=df['Grocery'].mean()
df['Grocery'].fillna(df1,inplace=True)

In [ ]:
df2=df['Frozen'].mean()
df['Frozen'].fillna(df2,inplace=True)

In [ ]:
df3=df['Detergents_Paper'].mean()
df['Detergents_Paper'].fillna(df3,inplace=True)

In [ ]:
df4=df['Delicassen'].mean()
df['Delicassen'].fillna(df4,inplace=True)

In [ ]:
df.isna().sum()

Channel             0
Region              0
Fresh               0
Milk                0
Grocery             0
Frozen              0
Detergents_Paper    0
Delicassen          0
dtype: int64

In [ ]:
df5=df.groupby('Channel') ['Channel'].count()
df5

Channel
1    282
2    134
Name: Channel, dtype: int64

In [ ]:
df6=pd.get_dummies(df5,{'Channel'})
df6

{'Channel'}_134  {'Channel'}_282
Channel                                  
1                      0                1
2                      1                0

In [ ]:
x=df.iloc[:,1:].values
y=df.iloc[:,0].values
x

array([[3.0000e+00, 1.2669e+04, 9.6560e+03, ..., 2.1400e+02, 2.6740e+03,
        1.3380e+03],
       [3.0000e+00, 7.0570e+03, 9.8100e+03, ..., 1.7620e+03, 3.2930e+03,
        1.7760e+03],
       [3.0000e+00, 6.3530e+03, 8.8080e+03, ..., 2.4050e+03, 3.5160e+03,
        7.8440e+03],
       ...,
       [3.0000e+00, 1.4531e+04, 1.5488e+04, ..., 4.3700e+02, 1.4841e+04,
        1.8670e+03],
       [3.0000e+00, 1.0290e+04, 1.9810e+03, ..., 1.0380e+03, 1.6800e+02,
        2.1250e+03],
       [3.0000e+00, 2.7870e+03, 1.6980e+03, ..., 6.5000e+01, 4.7700e+02,
        5.2000e+01]])

In [ ]:
y

array([2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1,
       2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1,
       1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       2, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1,
       2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1,
       2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1,

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[1.0000e+00, 8.0400e+03, 3.7950e+03, ..., 6.3400e+03, 9.1800e+02,
        2.9100e+02],
       [3.0000e+00, 2.2925e+04, 7.3498e+04, ..., 9.8700e+02, 2.0070e+04,
        9.0300e+02],
       [3.0000e+00, 3.7036e+04, 7.1520e+03, ..., 2.9950e+03, 2.0000e+01,
        3.0000e+00],
       ...,
       [3.0000e+00, 1.2238e+04, 7.1080e+03, ..., 1.0930e+03, 2.3280e+03,
        2.0790e+03],
       [3.0000e+00, 7.9600e+02, 5.8780e+03, ..., 3.4000e+02, 2.3200e+02,
        7.7600e+02],
       [3.0000e+00, 1.4438e+04, 2.2950e+03, ..., 3.2200e+03, 5.8500e+02,
        1.5610e+03]])

In [ ]:
x_test

array([[3.00000000e+00, 5.53100000e+03, 1.57260000e+04, 2.68700000e+04,
        2.36700000e+03, 1.37260000e+04, 4.46000000e+02],
       [2.00000000e+00, 2.43000000e+02, 1.29390000e+04, 8.85200000e+03,
        7.99000000e+02, 3.90900000e+03, 2.11000000e+02],
       [3.00000000e+00, 8.53300000e+03, 5.50600000e+03, 5.16000000e+03,
        1.34860000e+04, 1.37700000e+03, 1.49800000e+03],
       [3.00000000e+00, 1.55870000e+04, 1.01400000e+03, 3.97000000e+03,
        9.10000000e+02, 1.39000000e+02, 1.37800000e+03],
       [3.00000000e+00, 2.19000000e+02, 9.54000000e+03, 1.44030000e+04,
        2.83000000e+02, 7.81800000e+03, 1.56000000e+02],
       [3.00000000e+00, 6.60000000e+02, 8.49400000e+03, 1.86220000e+04,
        1.33000000e+02, 6.74000000e+03, 7.76000000e+02],
       [3.00000000e+00, 4.04800000e+03, 5.16400000e+03, 1.03910000e+04,
        1.30000000e+02, 8.13000000e+02, 1.79000000e+02],
       [1.00000000e+00, 1.10720000e+04, 5.98900000e+03, 5.61500000e+03,
        8.32100000e+03, 9

In [ ]:
y_train

array([1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1,
       1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1,
       2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2,
       1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2,
       2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1,
       2, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1,
       1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       2, 1, 2, 1, 1])

In [ ]:
y_test

array([2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1,
       2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1])

In [ ]:
#Normalization
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[0.00000000e+00, 7.16642294e-02, 2.91184261e-05, ...,
        1.72971048e-01, 2.24132863e-02, 6.00750939e-03],
       [1.00000000e+00, 2.04390627e-01, 5.71803360e-04, ...,
        2.63496672e-02, 4.91549089e-01, 1.87734668e-02],
       [1.00000000e+00, 3.30215430e-01, 5.52549385e-05, ...,
        8.13498042e-02, 4.16421713e-04, 0.00000000e+00],
       ...,
       [1.00000000e+00, 1.09096908e-01, 5.49123688e-05, ...,
        2.92530609e-02, 5.69517931e-02, 4.33041302e-02],
       [1.00000000e+00, 7.07101330e-03, 4.53359880e-05, ...,
        8.62800953e-03, 5.60944542e-03, 1.61243221e-02],
       [1.00000000e+00, 1.28713842e-01, 1.74399130e-05, ...,
        8.75126681e-02, 1.42563198e-02, 3.24989570e-02]])

In [ ]:
x_test

array([[1.00000000e+00, 4.92920070e-02, 1.22009320e-04, 2.89586859e-01,
        6.41485661e-02, 3.36150304e-01, 9.24071756e-03],
       [5.00000000e-01, 2.14002925e-03, 1.00310642e-04, 9.53792427e-02,
        2.12002520e-02, 9.56790123e-02, 4.33875678e-03],
       [1.00000000e+00, 7.60602062e-02, 4.24397168e-05, 5.55848971e-02,
        3.68703607e-01, 3.36566725e-02, 3.11848144e-02],
       [1.00000000e+00, 1.38959232e-01, 7.46646274e-06, 4.27584423e-02,
        2.42405982e-02, 3.33137370e-03, 2.86816854e-02],
       [1.00000000e+00, 1.92602632e-03, 7.38471314e-05, 1.55210882e-01,
        7.06675066e-03, 1.91431511e-01, 3.19148936e-03],
       [1.00000000e+00, 5.85833006e-03, 6.57033149e-05, 2.00685515e-01,
        2.95817470e-03, 1.65025475e-01, 1.61243221e-02],
       [1.00000000e+00, 3.60684096e-02, 3.97770158e-05, 1.11967406e-01,
        2.87600318e-03, 1.98412698e-02, 3.67125574e-03],
       [0.00000000e+00, 9.86999322e-02, 4.62001980e-05, 6.04891298e-02,
        2.27231642e-01, 2

In [ ]:
#Model Creation
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1,
       1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1,
       2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
mat=confusion_matrix(y_pred,y_test)
mat

array([[85,  5],
       [ 2, 33]])

In [ ]:
score=accuracy_score(y_test,y_pred)
score

0.944

In [ ]:
report=classification_report(y_pred,y_test)
print(report)

              precision    recall  f1-score   support

           1       0.98      0.94      0.96        90
           2       0.87      0.94      0.90        35

    accuracy                           0.94       125
   macro avg       0.92      0.94      0.93       125
weighted avg       0.95      0.94      0.94       125

